# Generated by Django 4.2.16 on 2025-02-25 20:15

from django.db import migrations


def populate_configuration(apps, schema_editor):
    Configuration = apps.get_model("configuration", "Configuration")

    # List of initial configuration entries
    initial_data = [
        {
            "key": "review_rate_limit_popup_message",
            "data_type": "html",
            "value": "<p>Volunteers can only accept {% configuration_value 'review_rate_limit' %} pages per minute.</p>\r\n<p>Please read all transcriptions completely to ensure they are whole and accurate. <a href=\"{% url 'how-to-review' %}\">See review instructions.</a></p>",
            "description": "Message shown in the pop-up when a user exceeds the review rate limit",
        },
        {
            "key": "review_rate_limit_popup_title",
            "data_type": "html",
            "value": "You cannot yet accept this page",
            "description": "Title of the error pop-up displayed when a user exceeds the review rate limit",
        },
        {
            "key": "review_rate_limit",
            "data_type": "number",
            "value": "4",
            "description": "Number of reviews allowed per minute",
        },
        {
            "key": "review_rate_limit_banner_message",
            "data_type": "html",
            "value": "Volunteers can only accept {% configuration_value 'review_rate_limit' %} pages per minute. See <a href=\"{% url 'how-to-review' %}\">review instructions</a>.",
            "description": "Message to display on the banner when a user exceeds the review rate limit",
        },
    ]

    # Insert data into the database
    for entry in initial_data:
        Configuration.objects.update_or_create(key=entry["key"], defaults=entry)


def revert_populate_configuration(apps, schema_editor):
    # We can't actually revert the data to the state it was before,
    # and there's no actual need to, but we need this function to be
    # able to reverse this migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_configuration, revert_populate_configuration),
    ]
