# Generated by Django 4.2.16 on 2025-03-03 20:51

from django.db import migrations


def populate_retry_configuration(apps, schema_editor):
    Configuration = apps.get_model("configuration", "Configuration")

    # List of initial retry configuration entries
    initial_data = [
        {
            "key": "asset_image_import_max_retries",
            "data_type": "number",
            "value": "3",
            "description": "The maximum number of times to retry downloading "
            "an asset image during import",
        },
        {
            "key": "asset_image_import_max_retry_delay",
            "data_type": "number",
            "value": "10",
            "description": "The number of minutes to wait before retrying downloading "
            "an image during import. A non-positive number will disable retries. Should "
            "not be greater than around 45 to avoid the system duplicating the task.",
        },
    ]

    # Insert data into the database
    for entry in initial_data:
        Configuration.objects.update_or_create(key=entry["key"], defaults=entry)


def revert_populate_retry_configuration(apps, schema_editor):
    # We can't actually revert the data to the state it was before,
    # and there's no actual need to, but we need this function to be
    # able to reverse this migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0002_populate_configurations"),
    ]

    operations = [
        migrations.RunPython(
            populate_retry_configuration, revert_populate_retry_configuration
        ),
    ]
