# Generated by Django 4.2.22 on 2025-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0004_alter_configuration_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("text", "Plain text"),
                    ("number", "Number"),
                    ("boolean", "Boolean"),
                    ("json", "JSON"),
                    ("html", "HTML"),
                    ("rate", "Rate"),
                ],
                default="text",
                help_text="Data type of the value",
                max_length=10,
            ),
        ),
    ]
