pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/LibraryOfCongress/concordia.git'
            }
        }
        stage('Deploy') {
            steps {
                sh 'cd concordia'
                sh 'docker-compose up -d'
            }
        }
    }
}