root: true
extends:
    - eslint:recommended
    - plugin:unicorn/recommended
plugins:
    - prettier
    - unicorn
rules:
    indent:
        # https://eslint.org/docs/4.0.0/rules/indent
        # Match defaults & Crockford but enable indentation for switch statement cases:
        - 2
        - 4
        - SwitchCase: 1
    'unicorn/prefer-query-selector': off # See https://github.com/sindresorhus/eslint-plugin-unicorn/issues/276
    'unicorn/prefer-node-append': off
    'unicorn/prefer-ternary': off
env:
    browser: true
    es6: true
parserOptions:
    sourceType: script
    ecmaVersion": '2018'
