extends:
    - stylelint-config-recommended
    - stylelint-config-standard-scss

plugins:
    - stylelint-value-no-unknown-custom-properties

rules:
    no-descending-specificity: null
    at-rule-no-unknown: null
    csstools/value-no-unknown-custom-properties: true
    scss/dollar-variable-empty-line-before: null
    property-no-vendor-prefix: null
