# Generated by Django 2.0.4 on 2018-04-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribr', '0004_branch_rickey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['title', 'sequence']},
        ),
        migrations.AlterModelOptions(
            name='subcollection',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='media_url',
            field=models.CharField(max_length=255),
        ),
    ]
