# Generated by Django 2.0.5 on 2018-05-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribr', '0005_auto_20180426_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='media_url',
            field=models.URLField(max_length=255),
        ),
    ]
