# Generated by Django 2.0.5 on 2018-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0002_auto_20180511_1722")]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="is_active",
            field=models.BooleanField(default=False),
        )
    ]
