# Generated by Django 2.0.5 on 2018-05-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0002_auto_20180511_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='media_url_test',
            field=models.CharField(default='media_url', max_length=255),
            preserve_default=False,
        ),
    ]
