# Generated by Django 2.0.9 on 2018-10-09 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0003_auto_20181004_2103")]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                help_text="A previous transcription record which is replaced by this one",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="concordia.Transcription",
            ),
        )
    ]
