# Generated by Django 2.0.7 on 2018-07-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0004_auto_20180712_1857")]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="status",
            field=models.CharField(
                choices=[
                    ("Edit", "Open for Edit"),
                    ("Submitted", "Submitted for Review"),
                    ("Completed", "Transcription Completed"),
                ],
                default="Edit",
                max_length=10,
            ),
        )
    ]
