# Generated by Django 2.0.7 on 2018-07-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0005_auto_20180713_1753")]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("Edit", "Open for Edit"),
                    ("Submitted", "Submitted for Review"),
                    ("Completed", "Transcription Completed"),
                ],
                default="Edit",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Edit", "Open for Edit"),
                    ("Submitted", "Submitted for Review"),
                    ("Completed", "Transcription Completed"),
                ],
                default="Edit",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Edit", "Open for Edit"),
                    ("Submitted", "Submitted for Review"),
                    ("Completed", "Transcription Completed"),
                ],
                default="Edit",
                max_length=10,
            ),
        ),
    ]
