# Generated by Django 2.0.9 on 2018-10-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0005_thumbnail_images'),
        ('concordia', '0004_auto_20181010_1715'),
    ]

    operations = [
    ]
