# Generated by Django 2.0.9 on 2018-10-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0006_project_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='thumbnail_image',
            field=models.ImageField(default='', upload_to='campaign-thumbs'),
            preserve_default=False,
        ),
    ]
