# Generated by Django 2.0.9 on 2018-10-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("concordia", "0007_thumbnail_images")]

    operations = [
        migrations.AlterModelOptions(name="asset", options={}),
        migrations.AlterModelOptions(
            name="resource", options={"ordering": ["campaign", "sequence"]}
        ),
        migrations.AlterUniqueTogether(
            name="resource", unique_together={("campaign", "sequence")}
        ),
    ]
