# Generated by Django 2.0.7 on 2018-07-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0008_auto_20180727_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinuse',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
