# Generated by Django 2.0.9 on 2018-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("concordia", "0008_auto_20181015_1711")]

    operations = [
        migrations.AddField(
            model_name="project", name="description", field=models.TextField(blank=True)
        )
    ]
