# Generated by Django 2.0.9 on 2018-10-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("concordia", "0009_project_description")]

    operations = [
        migrations.RemoveField(model_name="asset", name="resource_id"),
        migrations.AddField(
            model_name="asset",
            name="resource_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
