# Generated by Django 2.0.9 on 2018-10-22 15:30

from django.db import migrations


def handle_items_without_projects(apps, schema_editor):
    Item = apps.get_model("concordia", "Item")
    Item.objects.filter(project=None).delete()


class Migration(migrations.Migration):

    dependencies = [("concordia", "0009_project_description")]

    operations = [migrations.RunPython(handle_items_without_projects)]
