# Generated by Django 2.0.9 on 2018-10-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("concordia", "0010_auto_20181022_1530")]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="concordia.Project"
            ),
        )
    ]
