# Generated by Django 2.0.7 on 2018-08-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0011_auto_20180730_2046"),
        ("concordia", "0007_collection_s3_storage"),
    ]

    operations = []
