# Generated by Django 2.0.7 on 2018-08-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0007_collection_s3_storage'),
        ('concordia', '0011_auto_20180730_2046'),
    ]

    operations = [
    ]
