# Generated by Django 2.0.9 on 2018-10-22 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0010_auto_20181021_1659"),
        ("concordia", "0011_auto_20181022_1532"),
    ]

    operations = []
