# Generated by Django 2.0.7 on 2018-08-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0012_merge_20180807_1344"),
        ("concordia", "0012_merge_20180806_1254"),
    ]

    operations = []
