# Generated by Django 2.0.9 on 2018-10-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0012_merge_20181022_1554")]

    operations = [
        migrations.AlterField(
            model_name="resource", name="title", field=models.CharField(max_length=255)
        )
    ]
