# Generated by Django 2.0.7 on 2018-08-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0013_merge_20180808_1356")]

    operations = [
        migrations.AlterField(
            model_name="pageinuse",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        )
    ]
