# Generated by Django 2.0.8 on 2018-09-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0014_auto_20180904_1758")]

    operations = [
        migrations.AlterModelOptions(
            name="asset", options={"ordering": ["title", "sequence"]}
        ),
        migrations.AddField(
            model_name="asset",
            name="download_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="resource_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
