# Generated by Django 2.0.8 on 2018-09-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0015_auto_20180905_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='thumbnail_image',
            new_name='thumbnail_url',
        ),
    ]
