# Generated by Django 2.0.8 on 2018-09-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0016_auto_20180906_1720")]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="slug",
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="campaign", name="title", field=models.CharField(max_length=500)
        ),
        migrations.AlterField(
            model_name="project", name="slug", field=models.SlugField(max_length=500)
        ),
        migrations.AlterField(
            model_name="project", name="title", field=models.CharField(max_length=500)
        ),
    ]
