# Generated by Django 2.0.9 on 2018-11-20 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("concordia", "0016_auto_20181115_1803")]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                help_text="A previous transcription record which is replaced by this one",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="superseded_by",
                to="concordia.Transcription",
            ),
        )
    ]
