# Generated by Django 2.0.8 on 2018-09-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0017_auto_20180912_0229")]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="slug",
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="campaign", name="title", field=models.CharField(max_length=80)
        ),
        migrations.AlterField(
            model_name="project", name="slug", field=models.SlugField(max_length=80)
        ),
        migrations.AlterField(
            model_name="project", name="title", field=models.CharField(max_length=80)
        ),
    ]
