# Generated by Django 2.0.9 on 2018-11-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("concordia", "0018_auto_20181128_1611")]

    operations = [
        migrations.RemoveField(model_name="campaign", name="end_date"),
        migrations.RemoveField(model_name="campaign", name="start_date"),
    ]
