# Generated by Django 2.0.9 on 2018-11-28 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0018_simplepage"),
        ("concordia", "0018_auto_20181128_1611"),
    ]

    operations = []
