# Generated by Django 2.0.8 on 2018-09-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0020_auto_20180922_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='media_url',
            field=models.TextField(max_length=255, verbose_name='Path component of the URL'),
        ),
    ]
