# Generated by Django 2.0.8 on 2018-09-24 15:11

from django.db import migrations
from django.db.models import Q


def delete_bogons(apps, schema_editor):
    Asset = apps.get_model("concordia", "Asset")
    Asset.objects.filter(Q(project__isnull=True) | Q(item__isnull=True)).delete()


class Migration(migrations.Migration):

    dependencies = [("concordia", "0021_auto_20180922_0202")]

    operations = [migrations.RunPython(delete_bogons)]
