# Generated by Django 2.0.9 on 2018-12-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0021_sitereport")]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="ordering",
            field=models.IntegerField(
                default=0,
                help_text="Sort order override: lower values will be listed first",
            ),
        )
    ]
