# Generated by Django 2.2 on 2019-04-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0023_auto_20190130_1555")]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(allow_unicode=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="theme-thumbnails"
                    ),
                ),
            ],
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(name="resource", options={}),
        migrations.AlterModelOptions(
            name="sitereport", options={"ordering": ("created_on",)}
        ),
        migrations.RemoveField(model_name="project", name="category"),
        migrations.AlterField(
            model_name="asset",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="asset",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="resource",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="concordia.Campaign",
            ),
        ),
        migrations.AlterUniqueTogether(name="resource", unique_together=set()),
        migrations.AddField(
            model_name="project",
            name="themes",
            field=models.ManyToManyField(to="concordia.Theme"),
        ),
        migrations.AddField(
            model_name="resource",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="concordia.Theme",
            ),
        ),
    ]
