# Generated by Django 2.1.7 on 2019-02-21 00:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("concordia", "0023_auto_20190130_1555"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator("^[- _'\\w]{1,50}$")
                        ],
                    ),
                ),
                ("created_on", models.DateTimeField()),
                ("updated_on", models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="sitereport", options={"ordering": ("created_on",)}
        ),
        migrations.AlterField(
            model_name="asset",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="asset",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=80),
        ),
        migrations.AddField(
            model_name="assettag",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="concordia.Asset"
            ),
        ),
        migrations.AddField(
            model_name="assettag",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
