# Generated by Django 2.2 on 2019-04-19 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("concordia", "0023_auto_20190130_1555")]

    operations = [
        migrations.AlterModelOptions(
            name="sitereport", options={"ordering": ("created_on",)}
        )
    ]
