# Generated by Django 2.1.7 on 2019-02-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0023_auto_20190130_1555")]

    operations = [
        migrations.AlterModelOptions(
            name="sitereport", options={"ordering": ("created_on",)}
        ),
        migrations.AddField(
            model_name="asset",
            name="difficulty",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="asset",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=80),
        ),
    ]
