# Generated by Django 2.1.7 on 2019-02-21 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("concordia", "0024_auto_20190220_1915")]

    operations = [
        migrations.AddField(
            model_name="assettag",
            name="tag_text",
            field=models.CharField(
                default="",
                max_length=50,
                validators=[django.core.validators.RegexValidator("^[- _'\\w]{1,50}$")],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assettag",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="concordia.Tag",
            ),
        ),
    ]
