# Generated by Django 2.0.8 on 2018-09-24 20:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("concordia", "0024_auto_20180924_1529")]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                help_text="Raw metadata returned by the remote API",
                null=True,
            ),
        )
    ]
