# Generated by Django 2.0.8 on 2018-09-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0025_auto_20180924_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
