# Generated by Django 2.2 on 2019-04-23 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0025_auto_20190329_1705"),
        ("concordia", "0026_update_published_field_definition"),
    ]

    operations = []
