# Generated by Django 2.0.8 on 2018-09-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("concordia", "0026_auto_20180925_2000")]

    operations = [
        migrations.RenameField(
            model_name="campaign", old_name="is_publish", new_name="published"
        ),
        migrations.RenameField(
            model_name="item", old_name="is_publish", new_name="published"
        ),
        migrations.RenameField(
            model_name="project", old_name="is_publish", new_name="published"
        ),
        migrations.RemoveField(model_name="item", name="visible"),
    ]
