# Generated by Django 2.0.8 on 2018-09-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0027_auto_20180926_1705'),
        ('concordia', '0026_creategroups'),
    ]

    operations = [
    ]
