# Generated by Django 2.2 on 2019-04-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("concordia", "0027_merge_20190423_1657")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="year",
            field=models.CharField(blank=True, max_length=50),
        )
    ]
