# Generated by Django 2.2 on 2019-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0028_asset_year")]

    operations = [
        migrations.AddField(
            model_name="assettranscriptionreservation",
            name="reserve_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        )
    ]
