# Generated by Django 2.0.8 on 2018-09-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0028_merge_20180927_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='myfile',
        ),
    ]
