# Generated by Django 2.2 on 2019-04-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0028_asset_year"),
        ("concordia", "0024_auto_20190411_1514"),
    ]

    operations = []
