# Generated by Django 2.0.8 on 2018-09-28 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0028_merge_20180927_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[- _'\\w]{1,50}$")]),
        ),
    ]
