# Generated by Django 2.2 on 2019-05-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0029_merge_20190424_1509")]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="topic",
            name="short_description",
            field=models.TextField(blank=True),
        ),
    ]
