# Generated by Django 2.0.8 on 2018-09-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0029_remove_userprofile_myfile'),
        ('concordia', '0029_auto_20180928_1437'),
    ]

    operations = [
    ]
