# Generated by Django 2.0.8 on 2018-10-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0029_auto_20180928_1437"),
        ("concordia", "0029_remove_userprofile_myfile"),
    ]

    operations = []
