# Generated by Django 2.0.8 on 2018-10-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0030_merge_20181002_1350'),
        ('concordia', '0030_merge_20180928_1740'),
    ]

    operations = [
    ]
