# Generated by Django 2.2.1 on 2019-06-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0032_topic_ordering")]

    operations = [
        migrations.CreateModel(
            name="SimpleContentBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text=(
                            "Label that is used to refer to this content in the code"
                        ),
                        max_length=255,
                    ),
                ),
                ("body", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(name="topic", options={}),
    ]
