# Generated by Django 2.0.8 on 2018-10-02 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0032_auto_20181002_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinuse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
