# Generated by Django 2.2.2 on 2019-06-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("concordia", "0033_simple_content_blocks")]

    operations = [
        migrations.AlterField(
            model_name="sitereport",
            name="anonymous_transcriptions",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="assets_completed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="assets_in_progress",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="assets_not_started",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="assets_published",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="assets_total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="assets_unpublished",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="assets_waiting_review",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="distinct_tags",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="items_published",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="items_unpublished",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="projects_published",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="projects_unpublished",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="tag_uses",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="transcriptions_saved",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
