# Generated by Django 2.0.8 on 2018-10-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0033_auto_20181002_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='parent',
        ),
    ]
