# Generated by Django 2.2.2 on 2019-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0033_auto_20190611_1611")]

    operations = [
        migrations.AlterField(
            model_name="simplecontentblock",
            name="label",
            field=models.CharField(
                help_text="Label that is used to refer to this content in the code",
                max_length=255,
                unique=True,
            ),
        )
    ]
