# Generated by Django 2.0.8 on 2018-10-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("concordia", "0034_remove_transcription_parent")]

    operations = [
        migrations.AlterUniqueTogether(
            name="item", unique_together={("item_id", "project")}
        ),
        migrations.AlterUniqueTogether(
            name="asset", unique_together={("slug", "item")}
        ),
        migrations.RemoveField(model_name="asset", name="campaign"),
        migrations.RemoveField(model_name="asset", name="project"),
        migrations.RemoveField(model_name="item", name="campaign"),
    ]

