# Generated by Django 2.2.2 on 2019-06-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0035_legacy_simple_content_blocks")]

    operations = [
        migrations.AlterField(
            model_name="simplecontentblock",
            name="label",
            field=models.SlugField(
                help_text="Label that templates use to retrieve this block",
                max_length=255,
                unique=True,
            ),
        )
    ]
