# Generated by Django 2.2 on 2019-04-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0035_auto_20190221_1148")]

    operations = [
        migrations.AlterField(
            model_name="assettag",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="assettag",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
