# Generated by Django 2.0.8 on 2018-10-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0035_auto_20181002_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
