# Generated by Django 2.2.3 on 2019-07-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("concordia", "0036_auto_20190703_1203")]

    operations = [
        migrations.CreateModel(
            name="CarouselSlide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "ordering",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order: lower values will be listed first",
                    ),
                ),
                ("published", models.BooleanField(blank=True, default=False)),
                (
                    "overlay_position",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")], max_length=5
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("image_alt_text", models.TextField(blank=True)),
                (
                    "carousel_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="carousel-slides"
                    ),
                ),
                ("lets_go_url", models.CharField(max_length=255)),
            ],
        )
    ]
