# Generated by Django 2.0.8 on 2018-10-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0036_remove_item_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(help_text='Unique item ID assigned by the upstream source', max_length=100),
        ),
    ]
