# Generated by Django 2.2.2 on 2019-06-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("concordia", "0036_auto_20190621_1429")]

    operations = [
        migrations.RenameField(
            model_name="simplecontentblock", old_name="label", new_name="slug"
        )
    ]
