# Generated by Django 2.0.8 on 2018-10-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0031_merge_20181002_1846'),
        ('concordia', '0037_auto_20181002_1939'),
    ]

    operations = [
    ]
