# Generated by Django 2.2.7 on 2020-01-29 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0038_sitereport_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item", name="title", field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="concordia.Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="sitereport",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="concordia.Topic",
            ),
        ),
    ]
