# Generated by Django 2.0.8 on 2018-10-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordia', '0038_merge_20181002_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='s3_storage',
        ),
    ]
