# Generated by Django 2.0.9 on 2018-10-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("concordia", "0039_remove_campaign_s3_storage")]

    operations = [migrations.RemoveField(model_name="campaign", name="is_active")]
