# Generated by Django 2.2.7 on 2020-01-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0039_auto_20200129_1536"),
    ]

    operations = [
        migrations.AddField(
            model_name="assettranscriptionreservation",
            name="last_reserve_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
