# Generated by Django 2.2.7 on 2020-02-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0039_auto_20200129_1536"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item", name="title", field=models.CharField(max_length=600),
        ),
    ]
