# Generated by Django 2.2.7 on 2020-02-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0040_auto_20200130_1756"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=600),
        ),
    ]
