# Generated by Django 2.2.10 on 2020-03-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0041_auto_20200203_1351"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="unlisted",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="topic",
            name="unlisted",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
