# Generated by Django 2.2.7 on 2020-01-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0041_assettranscriptionreservation_tombstoned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assettranscriptionreservation",
            name="tombstoned",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
