# Generated by Django 2.2.7 on 2020-01-30 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0042_auto_20200130_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assettranscriptionreservation",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="concordia.Asset"
            ),
        ),
    ]
