# Generated by Django 2.2.11 on 2020-03-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0042_auto_20200316_1623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="published",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="published",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="unlisted",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="published",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="published",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="topic",
            name="published",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="topic",
            name="unlisted",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
