# Generated by Django 2.2.11 on 2020-03-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0043_auto_20200323_1729"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["id", "published", "transcription_status"],
                name="concordia_a_id_0c37bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["published", "unlisted"], name="concordia_c_publish_2c3b1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["published", "unlisted"], name="concordia_t_publish_7f5b9d_idx"
            ),
        ),
    ]
