# Generated by Django 2.2.11 on 2020-03-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0046_auto_20200323_1907"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(
                fields=["asset", "user"], name="concordia_t_asset_i_4fcaa1_idx"
            ),
        ),
    ]
