# Generated by Django 2.2.11 on 2020-03-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0048_auto_20200324_1820"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="published",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
