# Generated by Django 3.2.13 on 2022-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0051_asset_storage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={"ordering": ("sequence",)},
        ),
        migrations.AlterModelOptions(
            name="sitereport",
            options={"ordering": ("-created_on",)},
        ),
        migrations.AlterField(
            model_name="asset",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw metadata returned by the remote API",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
