# Generated by Django 3.2.14 on 2022-09-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0053_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="active",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
