# Generated by Django 3.2.14 on 2022-08-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0053_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
