# Generated by Django 3.2.15 on 2022-09-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0055_campaign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="completed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="launch_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
