# Generated by Django 3.2.15 on 2022-09-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0056_auto_20220922_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="resource_type",
            field=models.IntegerField(
                choices=[(1, "Related Link"), (2, "Completed Transcription Link")],
                default=1,
            ),
        ),
    ]
