# Generated by Django 3.2.14 on 2022-10-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0057_resource_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, default="banner_1", max_length=80, unique=True
            ),
            preserve_default=False,
        ),
    ]
