# Generated by Django 3.2.15 on 2022-12-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0059_resourcefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcefile",
            name="resource",
            field=models.FileField(upload_to="cm-uploads/resources/%Y/"),
        ),
    ]
