# Generated by Django 3.2.16 on 2023-01-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0059_sitereport_registered_contributors"),
        ("concordia", "0060_alter_resourcefile_resource"),
    ]

    operations = []
