# Generated by Django 3.2.15 on 2023-02-01 19:53

from django.db import migrations, models

import concordia.models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0060_alter_resourcefile_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcefile",
            name="path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="resourcefile",
            name="resource",
            field=models.FileField(
                upload_to=concordia.models.resource_file_upload_path
            ),
        ),
    ]
