# Generated by Django 3.2.15 on 2022-12-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0060_alter_resourcefile_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitereport",
            name="registered_contributors",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
