# Generated by Django 3.2.15 on 2023-02-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0061_auto_20230201_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcefile",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
