# Generated by Django 3.2.17 on 2023-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0062_resourcefile_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="alert_status",
            field=models.CharField(
                choices=[
                    ("DANGER", "Danger"),
                    ("INFO", "Information"),
                    ("SUCCESS", "Success"),
                    ("WARN", "Warning"),
                ],
                default="SUCCESS",
                max_length=7,
            ),
        ),
    ]
