# Generated by Django 3.2.14 on 2023-02-13 20:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("concordia", "0062_userretiredcampaign"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userretiredcampaign",
            unique_together={("user", "campaign")},
        ),
    ]
