# Generated by Django 3.2.16 on 2023-02-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0065_alter_userretiredcampaign_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignRetirementProgress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_total", models.IntegerField(default=0)),
                ("projects_removed", models.IntegerField(default=0)),
                ("item_total", models.IntegerField(default=0)),
                ("items_removed", models.IntegerField(default=0)),
                ("asset_total", models.IntegerField(default=0)),
                ("assets_removed", models.IntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concordia.campaign",
                    ),
                ),
            ],
        ),
    ]
