# Generated by Django 3.2.17 on 2023-02-17 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("concordia", "0065_alter_userretiredcampaign_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userretiredcampaign",
            options={"verbose_name": "user completed campaign count"},
        ),
        migrations.AlterField(
            model_name="userretiredcampaign",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="concordia.campaign",
                verbose_name="Campaign Id",
            ),
        ),
        migrations.AlterField(
            model_name="userretiredcampaign",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Id",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userretiredcampaign",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="userretiredcampaign",
            constraint=models.UniqueConstraint(
                fields=("user", "campaign"), name="user_profile_activity"
            ),
        ),
    ]
