# Generated by Django 3.2.16 on 2023-02-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0067_alter_campaignretirementprogress_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignretirementprogress",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
