# Generated by Django 3.2.16 on 2023-02-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0066_auto_20230217_1302"),
        ("concordia", "0068_campaignretirementprogress_complete"),
    ]

    operations = []
