# Generated by Django 3.2.16 on 2023-02-27 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0069_merge_20230224_1446"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={"permissions": [("retire_campaign", "Can retire campaign")]},
        ),
    ]
