# Generated by Django 3.2.16 on 2023-03-06 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0070_alter_campaign_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignretirementprogress",
            name="completed_on",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="campaignretirementprogress",
            name="removal_log",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="campaignretirementprogress",
            name="started_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
