# Generated by Django 3.2.18 on 2023-03-13 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0064_alter_banner_alert_status"),
        ("concordia", "0071_auto_20230306_1456"),
    ]

    operations = []
