# Generated by Django 3.2.18 on 2023-03-14 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("concordia", "0072_merge_20230313_1047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="alert_status",
            field=models.CharField(
                choices=[
                    ("DANGER", "Red"),
                    ("INFO", "Blue"),
                    ("SUCCESS", "Green"),
                    ("WARNING", "Grey"),
                ],
                default="SUCCESS",
                max_length=7,
                verbose_name="Color",
            ),
        ),
        migrations.CreateModel(
            name="UserProfileActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_count", models.IntegerField(blank=True, null=True)),
                ("asset_tag_count", models.IntegerField(blank=True, null=True)),
                (
                    "transcribe_count",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="transcription save/submit count",
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="transcription review count"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concordia.campaign",
                        verbose_name="Campaign Id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Id",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="userprofileactivity",
            constraint=models.UniqueConstraint(
                fields=("user", "campaign"), name="user_campaign_count"
            ),
        ),
    ]
