# Generated by Django 3.2.18 on 2023-03-14 13:41

from django.db import migrations


def populate_user_activity_table(apps, schema_editor):
    # Asset = apps.get_model("Concordia", "Asset")
    Campaign = apps.get_model("Concordia", "Campaign")
    # User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    # UserAssetTagCollection = apps.get_model("Concordia", "Campaign")
    UserProfileActivity = apps.get_model("Concordia", "Campaign")
    for campaign in Campaign.objects.all():
        # assets = Asset.objects.filter(item__project__campaign=campaign)
        # tag_collections = UserAssetTagCollection.objects.filter(asset__in=assets)
        # user_profile_activity = UserProfileActivity.objects.filter(campaign=campaign)

        # to_update = user_profile_activity.distinct()
        UserProfileActivity.objects.bulk_update([UserProfileActivity()])


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0073_auto_20230314_1327"),
    ]

    operations = [
        migrations.RunPython(populate_user_activity_table),
    ]
