# Generated by Django 3.2.18 on 2023-04-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0075_auto_20230327_1333"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitereport",
            name="report_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
