# Generated by Django 3.2.19 on 2023-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0079_auto_20230601_1234"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="ocr_generated",
            field=models.BooleanField(
                default=False,
                help_text="Flags transcription as generated directly by OCR",
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="ocr_originated",
            field=models.BooleanField(
                default=False,
                help_text="Flags transcription as originated from an OCR transcription",
            ),
        ),
    ]
