# Generated by Django 3.2.19 on 2023-07-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0080_auto_20230602_0920"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitereport",
            name="daily_active_users",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
