# Generated by Django 3.2.19 on 2023-06-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0080_auto_20230602_0920"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitereport",
            name="review_actions",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
