# Generated by Django 3.2.19 on 2023-07-03 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0080_auto_20230602_0920"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRetiredCampaign",
        ),
    ]
