# Generated by Django 3.2.19 on 2023-07-10 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0081_sitereport_review_actions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRetiredCampaign",
        ),
    ]
