# Generated by Django 3.2.19 on 2023-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0082_delete_userretiredcampaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitereport",
            name="daily_active_users",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
