# Generated by Django 3.2.20 on 2023-09-06 14:27

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0013_alter_user_email"),
        ("concordia", "0084_rename_review_actions_sitereport_daily_review_actions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SimpleContentBlock",
        ),
        migrations.CreateModel(
            name="ConcordiaUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
