# Generated by Django 3.2.20 on 2023-09-11 15:12

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("concordia", "0084_rename_review_actions_sitereport_daily_review_actions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="card_images"),
                ),
                ("title", models.CharField(max_length=80)),
                ("body_text", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CardFamily",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=80, unique=True),
                ),
                ("default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "card families",
            },
        ),
        migrations.CreateModel(
            name="ConcordiaUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="TutorialCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="concordia.card"
                    ),
                ),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concordia.cardfamily",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cardfamily",
            name="cards",
            field=models.ManyToManyField(
                through="concordia.TutorialCard", to="concordia.Card"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="card_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="concordia.cardfamily",
            ),
        ),
    ]
