# Generated by Django 3.2.23 on 2023-12-15 18:11

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("concordia", "0085_auto_20231016_1432"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcordiaUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="next_review_campaign",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="next_transcription_campaign",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
