# Generated by Django 3.2.20 on 2023-10-16 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0086_auto_20230911_1112"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="tutorialcard",
            options={"verbose_name_plural": "cards"},
        ),
    ]
