# Generated by Django 3.2.20 on 2023-10-31 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0085_auto_20231016_1432"),
        ("concordia", "0086_auto_20230911_1112"),
    ]

    operations = []
