# Generated by Django 3.2.24 on 2024-02-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0087_auto_20240213_0756"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplepage",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
