# Generated by Django 3.2.23 on 2023-11-17 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0087_merge_0085_auto_20231016_1432_0086_auto_20230911_1112"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="tutorialcard",
            options={"verbose_name_plural": "cards"},
        ),
    ]
