# Generated by Django 3.2.24 on 2024-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0088_alter_simplepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="image_alt_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
