# Generated by Django 3.2.23 on 2023-12-18 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0086_auto_20231215_1311"),
        ("concordia", "0088_auto_20231117_0737"),
    ]

    operations = []
