# Generated by Django 3.2.23 on 2023-12-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0089_merge_0086_auto_20231215_1311_0088_auto_20231117_0737"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("body", models.TextField(blank=True)),
                ("order", models.IntegerField(default=1)),
                ("link_text", models.CharField(blank=True, max_length=80, null=True)),
                ("link_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
