# Generated by Django 3.2.25 on 2024-04-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0089_campaign_image_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="disable_ocr",
            field=models.BooleanField(
                default=False, help_text="Turn OCR off for this asset"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="disable_ocr",
            field=models.BooleanField(
                default=False, help_text="Turn OCR off for all assets of this campaign"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="disable_ocr",
            field=models.BooleanField(
                default=False, help_text="Turn OCR off for all assets of this item"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="disable_ocr",
            field=models.BooleanField(
                default=False, help_text="Turn OCR off for all assets of this project"
            ),
        ),
    ]
