# Generated by Django 3.2.25 on 2024-04-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0089_campaign_image_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="disable_ocr",
            field=models.BooleanField(
                default=False, help_text="turn OCR off for this asset"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="disable_ocr",
            field=models.BooleanField(
                default=False,
                help_text="Turn OCR off for this descendants of this campaign",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="disable_ocr",
            field=models.BooleanField(
                default=False, help_text="Turn OCR off for this children of this item"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="disable_ocr",
            field=models.BooleanField(
                default=False,
                help_text="Turn OCR off for this descendants of this project",
            ),
        ),
    ]
