# Generated by Django 4.2.11 on 2024-05-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0090_auto_20240408_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplepage",
            name="guide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="concordia.guide",
            ),
        ),
    ]
