# Generated by Django 4.2.13 on 2024-05-09 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0090_auto_20240408_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="concordia.simplepage",
            ),
        ),
    ]
