# Generated by Django 3.2.23 on 2024-01-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0091_auto_20240104_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplepage",
            name="navigation",
            field=models.TextField(null=True),
        ),
    ]
