# Generated by Django 4.2.11 on 2024-05-06 13:59

from django.db import migrations


def set_guides(apps, schema_editor):
    Guide = apps.get_model("concordia", "Guide")
    SimplePage = apps.get_model("concordia", "SimplePage")
    for guide in Guide.objects.all():
        page = SimplePage.objects.get(title=guide.title)
        page.guide = guide
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0091_simplepage_guide"),
    ]

    operations = [
        migrations.RunPython(set_guides),
    ]
