# Generated by Django 3.2.23 on 2024-01-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0092_simplepage_navigation"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="image_alt_text",
            field=models.TextField(blank=True),
        ),
    ]
