# Generated by Django 4.2.13 on 2024-06-17 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0092_auto_20240509_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="campaign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="concordia.campaign",
            ),
        ),
    ]
