# Generated by Django 3.2.23 on 2024-02-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0093_card_image_alt_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simplepage",
            name="navigation",
        ),
    ]
