# Generated by Django 3.2.23 on 2024-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0094_remove_simplepage_navigation"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
