# Generated by Django 4.2.13 on 2024-06-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0094_alter_asset_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="rolled_back",
            field=models.BooleanField(
                default=False,
                help_text="Flags transcription as being the result of a rollback (undo)",
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="rolled_forward",
            field=models.BooleanField(
                default=False,
                help_text="Flags transcription as being the result of a rollforward (redo)",
            ),
        ),
    ]
