# Generated by Django 4.2.13 on 2024-06-26 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0095_transcription_rolled_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="The transcription source for the roll back or roll forward",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_of",
                to="concordia.transcription",
            ),
        ),
    ]
