# Generated by Django 3.2.23 on 2024-02-05 14:37

from django.db import migrations


def initialize_updated_on(apps, schema_editor):
    Card = apps.get_model("concordia", "Card")
    for card in Card.objects.all():
        if card.updated_on is None:
            card.save()


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0095_card_updated_on"),
    ]

    operations = [
        migrations.RunPython(
            initialize_updated_on, reverse_code=migrations.RunPython.noop
        ),
    ]
