# Generated by Django 4.2.13 on 2024-07-29 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("concordia", "0096_transcription_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitereport",
            options={"get_latest_by": "created_on", "ordering": ("-created_on",)},
        ),
        migrations.AddField(
            model_name="userprofile",
            name="review_count",
            field=models.IntegerField(
                default=0, verbose_name="transcription review count"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="transcribe_count",
            field=models.IntegerField(
                default=0, verbose_name="transcription save/submit count"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
