# Generated by Django 4.2.13 on 2024-07-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0096_transcription_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="concordia.project",
            ),
        ),
    ]
