# Generated by Django 4.2.16 on 2024-11-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0098_userprofile_create_and_population"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="display_on_homepage",
            field=models.BooleanField(default=True, verbose_name="Homepage"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="next_review_campaign",
            field=models.BooleanField(
                blank=True, db_index=True, default=False, verbose_name="Next-rev."
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="next_transcription_campaign",
            field=models.BooleanField(
                blank=True, db_index=True, default=False, verbose_name="Next-tran."
            ),
        ),
    ]
