# Generated by Django 4.2.16 on 2024-11-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0099_alter_campaign_display_on_homepage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchCenter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
            ],
        ),
    ]
