# Generated by Django 4.2.16 on 2024-11-19 17:15

from django.db import migrations

TITLES = (
    "American Folklife Center",
    "Law Library",
    "Manuscript",
    "Performing Arts",
    "Rare Book",
)


def forwards_func(apps, schema_editor):
    # create initial data
    ResearchCenter = apps.get_model("concordia", "ResearchCenter")
    db_alias = schema_editor.connection.alias
    ResearchCenter.objects.using(db_alias).bulk_create(
        [
            ResearchCenter(title="American Folklife Center"),
            ResearchCenter(title="Law Library"),
            ResearchCenter(title="Manuscript"),
            ResearchCenter(title="Performing Arts"),
            ResearchCenter(title="Rare Book"),
        ]
    )


def reverse_func(apps, schema_editor):
    ResearchCenter = apps.get_model("concordia", "ResearchCenter")
    db_alias = schema_editor.connection.alias
    for title in TITLES:
        ResearchCenter.objects.using(db_alias).filter(title=title).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0100_researchcenter"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
