# Generated by Django 4.2.16 on 2024-11-19 17:15

from django.db import migrations


def forwards_func(apps, schema_editor):
    # create initial data
    ResearchCenter = apps.get_model("concordia", "ResearchCenter")
    db_alias = schema_editor.connection.alias
    ResearchCenter.objects.using(db_alias).bulk_create(
        [
            ResearchCenter(title="American Folklife Center"),
            ResearchCenter(title="Law Library"),
            ResearchCenter(title="Manuscript"),
            ResearchCenter(title="Performing Arts"),
            ResearchCenter(title="Rare Book"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0100_researchcenter"),
    ]

    operations = [migrations.RunPython(forwards_func)]
