# Generated by Django 4.2.16 on 2024-11-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0101_auto_20241119_1215"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="research_centers",
            field=models.ManyToManyField(to="concordia.researchcenter"),
        ),
    ]
