# Generated by Django 4.2.16 on 2024-12-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0102_campaign_research_centers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=700),
        ),
    ]
