# Generated by Django 4.2.16 on 2025-04-04 19:09

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0104_nexttranscribabletopicasset_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="nextreviewablecampaignasset",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["transcriber_ids"], name="concordia_n_transcr_aafdba_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="nextreviewabletopicasset",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["transcriber_ids"], name="concordia_n_transcr_415832_gin"
            ),
        ),
    ]
