# Generated by Django 4.2.16 on 2025-04-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0106_alter_nextreviewablecampaignasset_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nextreviewablecampaignasset",
            options={"get_latest_by": "created_on", "ordering": ("created_on",)},
        ),
        migrations.AlterModelOptions(
            name="nextreviewabletopicasset",
            options={"get_latest_by": "created_on", "ordering": ("created_on",)},
        ),
        migrations.AlterModelOptions(
            name="nexttranscribablecampaignasset",
            options={"get_latest_by": "created_on", "ordering": ("created_on",)},
        ),
        migrations.AlterModelOptions(
            name="nexttranscribabletopicasset",
            options={"get_latest_by": "created_on", "ordering": ("created_on",)},
        ),
    ]
