# Generated by Django 4.2.16 on 2025-04-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0108_add_next_asset_cache_periodic_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nextreviewablecampaignasset",
            name="asset",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="concordia.asset"
            ),
        ),
        migrations.AlterField(
            model_name="nexttranscribabletopicasset",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="concordia.asset"
            ),
        ),
    ]
