# Generated by Django 4.2.20 on 2025-04-23 19:22

import storages.backends.s3
from django.db import migrations, models

import concordia.models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0109_alter_nextreviewablecampaignasset_asset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="media_url",
        ),
        migrations.AlterField(
            model_name="asset",
            name="storage_image",
            field=models.ImageField(
                max_length=255,
                storage=storages.backends.s3.S3Storage(querystring_auth=False),
                upload_to=concordia.models.Asset.get_storage_path,
            ),
        ),
    ]
