# Generated by Django 4.2.20 on 2025-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0110_remove_asset_media_url_alter_asset_storage_image"),
    ]

    operations = [
        # We need to update Django so it knows about our intermediate
        # model, but since we're re-using the existing intermediate
        # table, we don't want to change anything in the database itself
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No DB changes, only Django state
            state_operations=[
                migrations.CreateModel(
                    name="ProjectTopic",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=models.CASCADE, to="concordia.project"
                            ),
                        ),
                        (
                            "topic",
                            models.ForeignKey(
                                on_delete=models.CASCADE, to="concordia.topic"
                            ),
                        ),
                    ],
                    options={
                        "db_table": "concordia_project_topics",
                        "unique_together": {("project", "topic")},
                    },
                ),
                migrations.AlterField(
                    model_name="project",
                    name="topics",
                    field=models.ManyToManyField(
                        to="concordia.Topic",
                        through="concordia.ProjectTopic",
                    ),
                ),
            ],
        ),
    ]
