# Generated by Django 4.2.20 on 2025-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0111_auto_20250428_1023"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttopic",
            name="url_filter",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=20,
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Needs Review"),
                    ("completed", "Completed"),
                ],
                help_text="Optional filter on the status for this project-topic link",
            ),
        ),
    ]
