# Generated by Django 4.2.22 on 2025-08-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0115_alter_asset_storage_image_alter_banner_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="thumbnail_image",
            field=models.ImageField(blank=True, null=True, upload_to="item-thumbnails"),
        ),
    ]
