# Generated by Django 4.2.22 on 2025-08-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0116_item_thumbnail_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="storage_services_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
