# Generated by Django 4.2.22 on 2025-08-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0116_item_thumbnail_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projecttopic",
            options={"ordering": ("ordering",)},
        ),
        migrations.AddField(
            model_name="projecttopic",
            name="ordering",
            field=models.IntegerField(
                default=0,
                help_text="Sort order override: lower values will be listed first",
            ),
        ),
    ]
