# Generated by Django 4.2.22 on 2025-08-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0117_alter_projecttopic_options_projecttopic_ordering"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["item", "published", "transcription_status"],
                name="concordia_a_item_id_f10916_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["published", "campaign", "title"],
                name="concordia_p_publish_0a0f1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projecttopic",
            index=models.Index(
                fields=["topic", "project"], name="concordia_p_topic_i_bf12cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttopic",
            index=models.Index(
                fields=["topic", "ordering"], name="concordia_p_topic_i_dcbe8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttopic",
            index=models.Index(
                fields=["topic", "url_filter"], name="concordia_p_topic_i_ee5c9d_idx"
            ),
        ),
    ]
