# Generated by Django 4.2.22 on 2025-09-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0118_asset_concordia_a_item_id_f10916_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="asset",
            name="concordia_a_id_137ca8_idx",
        ),
        migrations.RemoveIndex(
            model_name="asset",
            name="concordia_a_item_id_f10916_idx",
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["item", "published", "transcription_status", "sequence"],
                name="concordia_a_item_id_0926c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["published", "transcription_status", "item", "sequence"],
                name="concordia_a_publish_b60d2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["item", "sequence"], name="concordia_a_item_id_24ea05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["campaign", "sequence"], name="concordia_a_campaig_d64e2f_idx"
            ),
        ),
    ]
