# Generated by Django 4.2.22 on 2025-09-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0119_remove_asset_concordia_a_id_137ca8_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitereport",
            name="assets_started",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
