# Generated by Django 4.2.22 on 2025-09-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0120_sitereport_assets_started"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyMetricsReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("FISCAL_YEAR", "Fiscal year"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("fiscal_year", models.IntegerField()),
                ("fiscal_quarter", models.IntegerField(blank=True, null=True)),
                ("month", models.IntegerField(blank=True, null=True)),
                ("assets_published", models.IntegerField(blank=True, null=True)),
                ("assets_started", models.IntegerField(blank=True, null=True)),
                ("assets_completed", models.IntegerField(blank=True, null=True)),
                ("users_activated", models.IntegerField(blank=True, null=True)),
                (
                    "anonymous_transcriptions",
                    models.IntegerField(blank=True, null=True),
                ),
                ("transcriptions_saved", models.IntegerField(blank=True, null=True)),
                ("tag_uses", models.IntegerField(blank=True, null=True)),
                (
                    "crowd_emails_and_libanswers_sent",
                    models.IntegerField(blank=True, null=True),
                ),
                ("crowd_visits", models.IntegerField(blank=True, null=True)),
                ("crowd_page_views", models.IntegerField(blank=True, null=True)),
                ("crowd_unique_visitors", models.IntegerField(blank=True, null=True)),
                (
                    "avg_visit_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "transcriptions_added_to_loc_gov",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "datasets_added_to_loc_gov",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ("period_start", "period_end", "period_type"),
                "indexes": [
                    models.Index(
                        fields=["period_type", "period_start", "period_end"],
                        name="concordia_k_period__d8d9b6_idx",
                    ),
                    models.Index(
                        fields=["period_type", "fiscal_year"],
                        name="concordia_k_period__3d99e1_idx",
                    ),
                    models.Index(
                        fields=["period_type", "fiscal_year", "fiscal_quarter"],
                        name="concordia_k_period__420f19_idx",
                    ),
                    models.Index(
                        fields=["period_type", "fiscal_year", "month"],
                        name="concordia_k_period__06112a_idx",
                    ),
                ],
                "unique_together": {("period_type", "period_start", "period_end")},
            },
        ),
    ]
