# Generated by Django 4.2.22 on 2025-10-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0121_keymetricsreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
