# Generated by Django 4.2.22 on 2025-10-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0122_alter_item_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignretirementprogress",
            options={"verbose_name_plural": "campaign retirement progresses"},
        ),
    ]
