# Generated by Django 4.2.26 on 2025-11-14 15:05

from django.db import migrations

TITLE = "Geography and Map"


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ResearchCenter = apps.get_model("concordia", "ResearchCenter")
    ResearchCenter.objects.using(db_alias).create(title=TITLE)


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ResearchCenter = apps.get_model("concordia", "ResearchCenter")
    ResearchCenter.objects.using(db_alias).get(title=TITLE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0124_update_periodic_task_paths"),
    ]

    operations = [migrations.RunPython(forwards, reverse_func)]
