# Generated by Django 4.2.24 on 2025-12-15 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concordia", "0125_update_userprofile_tasks"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameModel(
                    old_name="Resource",
                    new_name="HelpfulLink",
                ),
                migrations.RenameField(
                    model_name="helpfullink",
                    old_name="resource_type",
                    new_name="link_type",
                ),
                migrations.RenameField(
                    model_name="helpfullink",
                    old_name="resource_url",
                    new_name="link_url",
                ),
                migrations.RenameModel(
                    old_name="ResourceFile",
                    new_name="ConcordiaFile",
                ),
                migrations.RenameField(
                    model_name="concordiafile",
                    old_name="resource",
                    new_name="uploaded_file",
                ),
            ],
        ),
    ]
