# Generated by Django 4.2.24 on 2025-12-15 16:37

from django.db import migrations, models

import concordia.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "concordia",
            "0126_concordiafile_helpfullink_remove_resource_campaign_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="concordiafile",
                    name="uploaded_file",
                    field=models.FileField(
                        db_column="resource",
                        upload_to=concordia.models.resource_file_upload_path,
                    ),
                ),
                migrations.AlterField(
                    model_name="helpfullink",
                    name="link_type",
                    field=models.IntegerField(
                        choices=[
                            (1, "Related Link"),
                            (2, "Completed Transcription Link"),
                        ],
                        db_column="resource_type",
                        default=1,
                    ),
                ),
                migrations.AlterField(
                    model_name="helpfullink",
                    name="link_url",
                    field=models.URLField(db_column="resource_url"),
                ),
                migrations.AlterModelTable(
                    name="concordiafile",
                    table="concordia_resourcefile",
                ),
                migrations.AlterModelTable(
                    name="helpfullink",
                    table="concordia_resource",
                ),
            ],
        ),
    ]
