# Generated by Django 4.2.24 on 2025-12-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0127_alter_campaignretirementprogress_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignretirementprogress",
            options={"verbose_name_plural": "campaign retirement progress"},
        ),
    ]
