# Generated by Django 2.0.7 on 2018-07-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionItemAssetCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_slug", models.SlugField()),
                ("collection_item_identifier", models.CharField(max_length=50)),
                ("collection_item_asset_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CollectionTaskDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=50)),
                ("collection_slug", models.SlugField(unique=True)),
                ("collection_page_count", models.IntegerField()),
                ("collection_item_count", models.IntegerField()),
                ("collection_asset_count", models.IntegerField()),
                ("collection_task_id", models.CharField(max_length=100)),
            ],
        ),
    ]
