# Generated by Django 2.0.7 on 2018-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("importer", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="campaignitemassetcount",
            name="campaign_item_asset_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaigntaskdetails",
            name="campaign_asset_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaigntaskdetails",
            name="campaign_item_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaigntaskdetails",
            name="campaign_page_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaigntaskdetails",
            name="campaign_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
