# Generated by Django 2.0.7 on 2018-07-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("importer", "0002_auto_20180709_0833")]

    operations = [
        migrations.AlterField(
            model_name="campaignitemassetcount",
            name="campaign_item_asset_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="campaigntaskdetails",
            name="campaign_asset_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="campaigntaskdetails",
            name="campaign_item_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="campaigntaskdetails",
            name="campaign_page_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
