# Generated by Django 2.0.8 on 2018-08-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("importer", "0003_auto_20180709_0933")]

    operations = [
        migrations.RemoveField(
            model_name="campaignitemassetcount", name="campaign_slug"
        ),
        migrations.AddField(
            model_name="campaignitemassetcount",
            name="campaign_task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="importer.CampaignTaskDetails",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaignitemassetcount",
            name="item_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="campaigntaskdetails",
            name="project_name",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaigntaskdetails",
            name="project_slug",
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="campaigntaskdetails", name="campaign_page_count"
        ),
        migrations.AlterUniqueTogether(
            name="campaigntaskdetails",
            unique_together={("campaign_slug", "project_slug")},
        ),
    ]
