# Generated by Django 2.0.8 on 2018-08-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("importer", "0003_auto_20180709_0933")]

    operations = [
        migrations.RemoveField(
            model_name="collectionitemassetcount", name="collection_slug"
        ),
        migrations.AddField(
            model_name="collectionitemassetcount",
            name="collection_task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="importer.CollectionTaskDetails",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collectionitemassetcount",
            name="item_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="collectiontaskdetails",
            name="subcollection_name",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collectiontaskdetails",
            name="subcollection_slug",
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="collectiontaskdetails", name="collection_page_count"
        ),
        migrations.AlterUniqueTogether(
            name="collectiontaskdetails",
            unique_together={("collection_slug", "subcollection_slug")},
        ),
    ]
