# Generated by Django 2.0.8 on 2018-09-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("importer", "0014_auto_20180924_1943")]

    operations = [
        migrations.AlterField(
            model_name="importitem",
            name="completed",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the job completed without error",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importitem",
            name="failed",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the job failed due to an error",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importitem",
            name="last_started",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time when a worker started processing this job",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importitem",
            name="status",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Status message, if any, from the last worker",
            ),
        ),
        migrations.AlterField(
            model_name="importitem",
            name="task_id",
            field=models.UUIDField(
                blank=True,
                help_text="UUID of the last Celery task to process this record",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importitemasset",
            name="completed",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the job completed without error",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importitemasset",
            name="failed",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the job failed due to an error",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importitemasset",
            name="last_started",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time when a worker started processing this job",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importitemasset",
            name="status",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Status message, if any, from the last worker",
            ),
        ),
        migrations.AlterField(
            model_name="importitemasset",
            name="task_id",
            field=models.UUIDField(
                blank=True,
                help_text="UUID of the last Celery task to process this record",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="completed",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the job completed without error",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="failed",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the job failed due to an error",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="last_started",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time when a worker started processing this job",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Status message, if any, from the last worker",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="task_id",
            field=models.UUIDField(
                blank=True,
                help_text="UUID of the last Celery task to process this record",
                null=True,
            ),
        ),
    ]
