# Generated by Django 4.2.16 on 2025-02-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0001_squashed_0015_auto_20180925_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="importitem",
            name="failure_reason",
            field=models.CharField(
                blank=True, choices=[("Image", "Image")], default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="importitemasset",
            name="failure_reason",
            field=models.CharField(
                blank=True, choices=[("Image", "Image")], default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="failure_reason",
            field=models.CharField(
                blank=True, choices=[("Image", "Image")], default="", max_length=50
            ),
        ),
    ]
