# Generated by Django 4.2.16 on 2025-03-03 20:49

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0016_importitem_failure_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importitem",
            name="failure_history",
            field=models.JSONField(
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Information about previous failures of the task, if any",
            ),
        ),
        migrations.AddField(
            model_name="importitem",
            name="retry_count",
            field=models.IntegerField(
                default=0, help_text="Number of times the task was retried"
            ),
        ),
        migrations.AddField(
            model_name="importitemasset",
            name="failure_history",
            field=models.JSONField(
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Information about previous failures of the task, if any",
            ),
        ),
        migrations.AddField(
            model_name="importitemasset",
            name="retry_count",
            field=models.IntegerField(
                default=0, help_text="Number of times the task was retried"
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="failure_history",
            field=models.JSONField(
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Information about previous failures of the task, if any",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="retry_count",
            field=models.IntegerField(
                default=0, help_text="Number of times the task was retried"
            ),
        ),
        migrations.AlterField(
            model_name="importitem",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[("Image", "Image"), ("Retries", "Retries")],
                default="",
                help_text="Reason the task failed, if one was provided",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="importitemasset",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[("Image", "Image"), ("Retries", "Retries")],
                default="",
                help_text="Reason the task failed, if one was provided",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[("Image", "Image"), ("Retries", "Retries")],
                default="",
                help_text="Reason the task failed, if one was provided",
                max_length=50,
            ),
        ),
    ]
