# Generated by Django 4.2.16 on 2025-03-06 16:04

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0103_alter_item_title"),
        ("importer", "0017_importitem_failure_history_importitem_retry_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importitem",
            name="status_history",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Previous statuses on the task, if any",
            ),
        ),
        migrations.AddField(
            model_name="importitemasset",
            name="status_history",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Previous statuses on the task, if any",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="status_history",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Previous statuses on the task, if any",
            ),
        ),
        migrations.AlterField(
            model_name="importitem",
            name="failure_history",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Information about previous failures of the task, if any",
            ),
        ),
        migrations.AlterField(
            model_name="importitem",
            name="retry_count",
            field=models.IntegerField(
                blank=True, default=0, help_text="Number of times the task was retried"
            ),
        ),
        migrations.AlterField(
            model_name="importitemasset",
            name="failure_history",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Information about previous failures of the task, if any",
            ),
        ),
        migrations.AlterField(
            model_name="importitemasset",
            name="retry_count",
            field=models.IntegerField(
                blank=True, default=0, help_text="Number of times the task was retried"
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="failure_history",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Information about previous failures of the task, if any",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="retry_count",
            field=models.IntegerField(
                blank=True, default=0, help_text="Number of times the task was retried"
            ),
        ),
        migrations.CreateModel(
            name="VerifyAssetImageJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "last_started",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time when a worker started processing this job",
                        null=True,
                    ),
                ),
                (
                    "completed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when the job completed without error",
                        null=True,
                    ),
                ),
                (
                    "failed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when the job failed due to an error",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Status message, if any, from the last worker",
                    ),
                ),
                (
                    "task_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the last Celery task to process this record",
                        null=True,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[("Image", "Image"), ("Retries", "Retries")],
                        default="",
                        help_text="Reason the task failed, if one was provided",
                        max_length=50,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Number of times the task was retried",
                    ),
                ),
                (
                    "failure_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Information about previous failures of the task, if any",
                    ),
                ),
                (
                    "status_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Previous statuses on the task, if any",
                    ),
                ),
                ("batch", models.UUIDField(blank=True, editable=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concordia.asset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DownloadAssetImageJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "last_started",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time when a worker started processing this job",
                        null=True,
                    ),
                ),
                (
                    "completed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when the job completed without error",
                        null=True,
                    ),
                ),
                (
                    "failed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when the job failed due to an error",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Status message, if any, from the last worker",
                    ),
                ),
                (
                    "task_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the last Celery task to process this record",
                        null=True,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[("Image", "Image"), ("Retries", "Retries")],
                        default="",
                        help_text="Reason the task failed, if one was provided",
                        max_length=50,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Number of times the task was retried",
                    ),
                ),
                (
                    "failure_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Information about previous failures of the task, if any",
                    ),
                ),
                (
                    "status_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Previous statuses on the task, if any",
                    ),
                ),
                ("batch", models.UUIDField(blank=True, editable=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concordia.asset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
