# Generated by Django 4.2.16 on 2025-03-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0018_importitem_status_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadassetimagejob",
            name="batch",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="verifyassetimagejob",
            name="batch",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
