# Generated by Django 4.2.16 on 2025-03-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0103_alter_item_title"),
        ("importer", "0019_alter_downloadassetimagejob_batch_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="downloadassetimagejob",
            unique_together={("asset", "batch")},
        ),
        migrations.AlterUniqueTogether(
            name="verifyassetimagejob",
            unique_together={("asset", "batch")},
        ),
    ]
