# Generated by Django 4.2.22 on 2025-08-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0020_alter_downloadassetimagejob_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importitemasset",
            name="storage_services_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
