Description: >
    This template deploys an elasticache cluster to the provided VPC and subnets

Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    SecurityGroup:
        Description: Select the Security Group to use for the ECS cluster hosts
        Type: AWS::EC2::SecurityGroup::Id

    CacheNodeType:
        Type: String
        Default: cache.m5.large

Resources:
    RedisService:
        Type: AWS::ElastiCache::ReplicationGroup
        Properties:
            ReplicationGroupDescription: Feature branch Valkey cluster
            SecurityGroupIds:
                - !Ref 'SecurityGroup'
            CacheSubnetGroupName: 'crowd-cache-1frtjeewr57u7'
            CacheNodeType: !Ref 'CacheNodeType'
            CacheParameterGroupName: 'default.valkey8.0.1'
            ReplicationGroupId: !Sub '${EnvironmentName}-valkey'
            EngineVersion: '8.0.1'
            Engine: valkey
            AutoMinorVersionUpgrade: true
            NumCacheClusters: 1
            SnapshotRetentionLimit: 1

Outputs:
    RedisAddress:
        Description: Primary endpoint address
        Value: !GetAtt 'RedisService.PrimaryEndPoint.Address'

    RedisPort:
        Description: Primary endpoint port
        Value: !GetAtt 'RedisService.PrimaryEndPoint.Port'
