Description: This template deploys an Ubuntu jenkins server in the default VPC.

Resources:
    Jenkins:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: 'ami-042e8287309f5df03'
            InstanceType: 't2.large'
            IamInstanceProfile: 'concordia-jenkins-ec2-role'
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 128
                      VolumeType: gp2
                      DeleteOnTermination: true
            NetworkInterfaces:
                - AssociatePublicIpAddress: true
                  DeviceIndex: '0'
                  GroupSet:
                      - 'sg-f7985fb9'
                  SubnetId: 'subnet-3748107d'
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash -xe
                    echo "Running userdata for ${AWS::StackName}"
                    wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -
                    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
                    sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
                    add-apt-repository \
                      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                      $(lsb_release -cs) \
                      stable"
                    apt-get update
                    apt-get install -qy -o Dpkg::Options::='--force-confnew' \
                      python3 python3-dev python3-venv python3-pip \
                      libtiff-dev libjpeg-dev libopenjp2-7-dev libwebp-dev zlib1g-dev \
                      graphviz apt-transport-https libpq-dev \
                      ca-certificates \
                      curl \
                      gnupg-agent \
                      software-properties-common \
                      docker-ce docker-ce-cli containerd.io \
                      openjdk-8-jdk jenkins \
                      nginx awscli
                    usermod -aG docker jenkins
                    snap install postgresql96
                    pip3 install awscli --upgrade
            Tags:
                - Key: Name
                  Value: Jenkins
                - Key: Environment
                  Value: dev
