Description: This template deploys an Ubuntu jenkins server in the default VPC.

Parameters:

    KeyPairName:
        Description: key pair (within this region) for EC2 instance access
        Type: String


Resources:
    Jenkins:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: 'ami-07d0cf3af28718ef8'
            InstanceType: 't2.large'
            IamInstanceProfile: 'concordia-jenkins-ec2-role'
            KeyName:
                Ref: KeyPairName
            NetworkInterfaces:
                - AssociatePublicIpAddress: true
                  DeviceIndex: '0'
                  GroupSet:
                    - 'sg-f7985fb9'
                  SubnetId: 'subnet-3748107d'
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash -xe
                    echo "Running userdata for ${AWS::StackName}"
                    wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -
                    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
                    sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
                    add-apt-repository \
                      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                      $(lsb_release -cs) \
                      stable"
                    apt-get update
                    apt-get install -qy -o Dpkg::Options::='--force-confnew' \
                      python3 python3-dev python3-venv python3-pip \
                      libtiff-dev libjpeg-dev libopenjp2-7-dev libwebp-dev zlib1g-dev \
                      graphviz apt-transport-https \
                      ca-certificates \
                      curl \
                      gnupg-agent \
                      software-properties-common \
                      docker-ce docker-ce-cli containerd.io \
                      openjdk-8-jdk jenkins \
                      nginx
                    usermod -aG docker jenkins
#                    systemctl start jenkins
#                    systemctl enable jenkins
#                    systemctl start docker
#                    systemctl enable docker
            Tags:
                - Key: Name
                  Value: Jenkins
                - Key: Environment
                  Value: dev
