Description: >
    This template contains the security groups required by our entire stack.
    We create them in a seperate nested template, so they can be referenced
    by all of the other nested templates.

Parameters:
    
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    
    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the security groups should be deployed to

    PublicSubnet1:
        Description: A reference to the public subnet in the 1st Availability Zone
        Type: AWS::EC2::Subnet::Id

    PublicSubnet2: 
        Description: A reference to the public subnet in the 2nd Availability Zone
        Type: AWS::EC2::Subnet::Id

    PrivateSubnet1:
        Description: A reference to the private subnet in the 1st Availability Zone
        Type: AWS::EC2::Subnet::Id

    PrivateSubnet2: 
        Description: A reference to the private subnet in the 2nd Availability Zone
        Type: AWS::EC2::Subnet::Id

Resources:

    NetworkAcl:
        Type: AWS::EC2::NetworkAcl
        Properties:
            VpcId:
                Ref: VPC
            Tags:
            - Key: Name
              Value: !Ref EnvironmentName

    # TODO: Update these ACLs to the latest OCIO standard ones
    # NOTE: These rules are for dev / test / stage only

    acl4:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Egress: 'true'
            Protocol: "-1"
            RuleAction: allow
            RuleNumber: '100'
            NetworkAclId: !Ref NetworkAcl
    acl5:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 140.147.236.152/32
            Protocol: "-1"
            RuleAction: deny
            RuleNumber: '10'
            NetworkAclId: !Ref NetworkAcl
    acl6:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 140.147.236.214/32
            Protocol: "-1"
            RuleAction: deny
            RuleNumber: '11'
            NetworkAclId: !Ref NetworkAcl
    acl7:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 140.147.0.0/16
            Protocol: '6'
            RuleAction: allow
            RuleNumber: '100'
            PortRange:
                From: '22'
                To: '22'
            NetworkAclId:
                Ref: NetworkAcl
    acl8:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Protocol: '6'
            RuleAction: allow
            RuleNumber: '110'
            PortRange:
                From: '1024'
                To: '65535'
            NetworkAclId:
                Ref: NetworkAcl
    acl9:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Protocol: '6'
            RuleAction: allow
            RuleNumber: '200'
            PortRange:
                From: '80'
                To: '80'
            NetworkAclId: !Ref NetworkAcl
    acl10:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Protocol: '6'
            RuleAction: allow
            RuleNumber: '210'
            PortRange:
                From: '443'
                To: '443'
            NetworkAclId: !Ref NetworkAcl

    acl11:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Protocol: "-1"
            RuleAction: allow
            RuleNumber: '300'
            NetworkAclId: !Ref NetworkAcl

    subnetacl5:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref NetworkAcl
        SubnetId: !Ref PrivateSubnet1

    subnetacl6:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref NetworkAcl
        SubnetId: !Ref PrivateSubnet2

    subnetacl7:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref NetworkAcl
        SubnetId: !Ref PublicSubnet1

    subnetacl8:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref NetworkAcl
        SubnetId: !Ref PublicSubnet2
