# Generated by Django 2.0.7 on 2018-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemassetcount',
            name='collection_item_asset_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectiontaskdetails',
            name='collection_asset_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectiontaskdetails',
            name='collection_item_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectiontaskdetails',
            name='collection_page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectiontaskdetails',
            name='collection_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
