name: 'Build'

on:
    workflow_dispatch:
    push:
        branches: [release]
    pull_request:
        branches: [main, 'feature-*']

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Install system packages
              run: |
                  sudo apt-get install -qy libmemcached-dev libz-dev libfreetype6-dev libtiff-dev \
                    libjpeg-dev libopenjp2-7-dev libwebp-dev zlib1g-dev libpq-dev

            - name: Install node and npm
              uses: actions/setup-node@v3
              with:
                  node-version: '12'

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  # Semantic version range syntax or exact version of a Python version
                  python-version: '3.10'
                  # Optional - x64 or x86 architecture, defaults to x64
                  architecture: 'x64'

            - name: Display Python version
              run: python -c "import sys; print(sys.version)"

            - name: Initialize venv install Dependencies
              run: |
                  python3 -m venv venv-1
                  source venv-1//bin/activate
                  python3 -m pip install --upgrade pip
                  pip3 install -U packaging
                  pip3 install -U setuptools
                  pip3 install -U pipenv
                  pipenv install --dev --system --deploy
                  python3 setup.py build

            - name: build containers
              run: |
                  docker build -t concordia .
                  docker build -t concordia/importer --file importer/Dockerfile .
                  docker build -t concordia/celerybeat --file celerybeat/Dockerfile .
