name: 'Build'

on:
    workflow_dispatch:
    push:
        branches: [release]
        paths-ignore:
            - docs/**
            - README.md
            - .github/**
            - cloudformation/**
            - db_scripts/**
            - jenkins/**
            - kibana-proxy/**
            - postgresql/**

    pull_request:
        branches: [main, 'feature-*']
        paths-ignore:
            - docs/**
            - README.md
            - .github/**
            - cloudformation/**
            - db_scripts/**
            - jenkins/**
            - kibana-proxy/**
            - postgresql/**

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Install system packages
              run: |
                  sudo apt-get update -qy && sudo apt-get dist-upgrade -qy && sudo apt-get install -qy \
                  libmemcached-dev libz-dev libfreetype6-dev libtiff-dev \
                  libjpeg-dev libopenjp2-7-dev libwebp-dev zlib1g-dev libpq-dev

            - name: Install node and npm
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                  # Semantic version range syntax or exact version of a Python version
                  python-version: '3.10'
                  # Optional - x64 or x86 architecture, defaults to x64
                  architecture: 'x64'

            - name: Display Python version
              run: python -c "import sys; print(sys.version)"

            - name: Initialize install Python Dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install -U packaging
                  pip3 install -U setuptools
                  pip3 install -U pipenv
                  pipenv install --dev --system --deploy
                  python3 setup.py build

            - name: build containers
              run: |
                  docker build -t concordia .
                  docker build -t concordia/importer --file importer/Dockerfile .
                  docker build -t concordia/celerybeat --file celerybeat/Dockerfile .
