name: 'Build and Test'

on:
    workflow_dispatch:
    push:
        branches: [main, release]
    pull_request:
        branches: [main]
    schedule:
        - cron: '20 22 * * 2'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 3
            matrix:
                python-version: [3.8, 3.9, 3.10]

        steps:
            - name: Install system packages
              run: |
                  sudo apt-get install -qy libmemcached-dev libz-dev libfreetype6-dev libtiff-dev libjpeg-dev libopenjp2-7-dev libwebp-dev zlib1g-dev libpq-dev

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Dependencies
              run: |
                  python3 -m pip3 install --upgrade pip
                  pip3 install -U packaging
                  pip3 install -U setuptools
                  pip3 install -U pipenv
                  pipenv install --dev --system --deploy
                  python3 setup.py build

            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag concordia:$(date +%s) .

            - name: Run Tests
              run: |
                  docker-compose up -d db
                  export DJANGO_SETTING_MODULE=concordia.settings_test
                  pipenv run manage.py test concordia
