name: pip-audit

on:
    workflow_dispatch:
    push:
        branches: [main, release]
    pull_request:
        branches: [main]

jobs:
    pip-audit:
        steps:
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.10 # change to your required version of Python

            - name: 'Generate requirements.txt'
              run: |
                  pipx run pipfile-requirements Pipfile.lock > requirements.txt

            - uses: pypa/gh-action-pip-audit@v1.0.8
              with:
                  inputs: requirements.txt
