name: pip-audit

on:
    workflow_dispatch:
    pull_request:
        branches: [main, release]
        paths-ignore:
            - docs/**
            - README.md
            - .github/**
            - cloudformation/**
            - db_scripts/**
            - jenkins/**
            - search-proxy/**
            - postgresql/**

jobs:
    pip-audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: 'Generate requirements.txt'
              run: |
                  pipx run pipfile-requirements Pipfile.lock > requirements.txt

            - uses: pypa/gh-action-pip-audit@v1.1.0
              with:
                  inputs: requirements.txt
                  ignore-vulns: |
                      PYSEC-2023-312
