name: 'Deploy to production'

on:
    workflow_dispatch:

env:
    AWS_REGION: us-east-1

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        name: Deploy to Production
        runs-on: ubuntu-latest
        environment:
            name: production

        steps:
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}
                  role-session-name: github_to_aws_deploy

            - name:
              env:
                  CLUSTER: ${{ secrets.CLUSTER }}
                  TARGET_SERVICE_A: ${{ secrets.TARGET_SERVICE_A }}
                  TARGET_SERVICE: ${{ secrets.TARGET_SERVICE }}
              run: |
                  aws ecs update-service --region ${{ env.AWS_REGION }} --force-new-deployment --cluster $CLUSTER --service $TARGET_SERVICE_A
                  aws ecs update-service --region ${{ env.AWS_REGION }} --force-new-deployment --cluster $CLUSTER --service $TARGET_SERVICE
